rootProject.name = 'AzuraBedWars'

include (
        'azurabedwars-dashboard',
        'azurabedwars-loader',
        'azurabedwars-plugin',
        'azurabedwars-plugin:core',
        'azurabedwars-plugin:1_8_R3',
        'azurabedwars-plugin:1_9_R1',
        'azurabedwars-plugin:1_9_R2',
        'azurabedwars-plugin:v1_11_R1',
        'azurabedwars-plugin:v1_12_R1',
        'azurabedwars-plugin:v1_13_R1',
        'azurabedwars-plugin:v1_13_R2',
        'azurabedwars-plugin:1_20_R1',
        'azurabedwars-plugin:1_20_R2',
        'azurabedwars-plugin:1_20_R3',
        'azurabedwars-plugin:1_20_R4',
        'azurabedwars-plugin:1_21_R1',
        'azurabedwars-plugin:1_21_R2',
        'azurabedwars-plugin:1_21_R3',
        'azurabedwars-plugin:1_21_R4',
        'azurabedwars-plugin:1_21_R5'
)
