name: AzuraBedWars
version: ${version}
main: cc.azuramc.bedwars.AzuraBedWars
authors: [An5w1r_]
api-version: 1.13
commands:
  start:
    description: Start a game
    usage: /<command>
    permission: azura.bw.user